//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bilet_table
    {
        public int id { get; set; }
        public Nullable<int> form_id { get; set; }
        public Nullable<int> to_id { get; set; }
        public Nullable<System.DateTime> date_from { get; set; }
        public Nullable<double> price { get; set; }
        public string type { get; set; }
        public Nullable<System.DateTime> date_to { get; set; }
    
        public virtual Countries_table Countries_table { get; set; }
        public virtual Countries_table Countries_table1 { get; set; }
    }
}
