//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDsite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AirWEntities : DbContext
    {
        public AirWEntities()
            : base("name=AirWEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bilet_table> Bilet_table { get; set; }
        public virtual DbSet<Countries_table> Countries_table { get; set; }
        public virtual DbSet<persons_table> persons_table { get; set; }
        public virtual DbSet<Place_table> Place_table { get; set; }
    }
}
