//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class persons_table
    {
        public int id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string gender { get; set; }
        public string phone_namber { get; set; }
        public string email { get; set; }
        public string password { get; set; }
    }
}
