//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place_table
    {
        public int id { get; set; }
        public string place_name { get; set; }
        public Nullable<int> id_bilet { get; set; }
        public Nullable<int> id_person { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Bilet_table Bilet_table { get; set; }
        public virtual persons_table persons_table { get; set; }
    }
}
